---
:sshPrivateKeyPath: ./DemandCubePlaybooks/roles/teamaccess/files/teamaccess
:digitalOceanToken: 4af329d2baa4686af5ef372006389680197d1be905db948043679961a050b3ad
:intnetName: neverwinterDP
machines:
- name: generic
  ram: 512MB
- name: elasticsearch
  ram: 512MB
