---
:sshPrivateKeyPath: ./DemandCubePlaybooks/roles/teamaccess/files/teamaccess
:digitalOceanToken: TOKENGOESHERE
:intnetName: neverwinterDP
machines:
- name: generic
  ram: 512MB
- name: elasticsearch
  ram: 512MB
